apiVersion: v2
name: catalog
version: 0.6.0
description: BlueCompute Catalog Microservice
home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-catalog
maintainers:
  - name: Fabio Gomez
    email: fabio.gomez@ieee.org
    url: https://github.com/fabiogomezdiaz